// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXX9pOYno-54SkD5cNfcbF1wkapl2A-Eg',
    appId: '1:118836098367:web:cdb35fda233becba374f8a',
    messagingSenderId: '118836098367',
    projectId: 'myubatplus',
    authDomain: 'myubatplus.firebaseapp.com',
    storageBucket: 'myubatplus.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD76UH5muGdWATYOfuUpghq04gOUSPkQI4',
    appId: '1:118836098367:android:d36eae637e5018c4374f8a',
    messagingSenderId: '118836098367',
    projectId: 'myubatplus',
    storageBucket: 'myubatplus.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwnm8UWZlrrVMGZr_bdPnABw8JWPgk4Ks',
    appId: '1:118836098367:ios:2616c64c20674984374f8a',
    messagingSenderId: '118836098367',
    projectId: 'myubatplus',
    storageBucket: 'myubatplus.firebasestorage.app',
    iosBundleId: 'com.example.mysejahteraClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwnm8UWZlrrVMGZr_bdPnABw8JWPgk4Ks',
    appId: '1:118836098367:ios:2616c64c20674984374f8a',
    messagingSenderId: '118836098367',
    projectId: 'myubatplus',
    storageBucket: 'myubatplus.firebasestorage.app',
    iosBundleId: 'com.example.mysejahteraClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXX9pOYno-54SkD5cNfcbF1wkapl2A-Eg',
    appId: '1:118836098367:web:146f80f53be13152374f8a',
    messagingSenderId: '118836098367',
    projectId: 'myubatplus',
    authDomain: 'myubatplus.firebaseapp.com',
    storageBucket: 'myubatplus.firebasestorage.app',
  );
}
